### ISSUE TITLE
Integration not working for RingCentral UK Accounts

### ISSUE THREAD

**Issue by DylanM72** [ringcentral/pipedrive-embeddable-ringcentral-phone-spa#1]
Integration not working for RingCentral UK Accounts.

**Comment by embbnux** [comment]
@DylanM72 Could you provide us more detailed information such as any error messages or screenshots?

**Comment by GiffordChester** [comment]
Hey @embbnux, please see attached screenshot regarding @DylanM72 concern.
![pipedriveforuk](https://user-images.githubusercontent.com/47609089/52735332-39949600-2f7c-11e9-9511-20ce2d87348a.png)

**Comment by FilipinaW** [comment]
I'm in Canada, and have the same issue.  Everyone is getting above error when tyring to sign into RingCentral through this Chrome extension.

**Comment by zxdong262** [comment]
Hi @GiffordChester Can you open developer tool, give a screenshot of console log when this error happens?

**Comment by zxdong262** [comment]
@DylanM72 @FilipinaW @GiffordChester Admin confirmed it is all supported for UK/CA.
Can you send me your login username or phone number? So I can check more data about this. You can send email to drake.zhao@ringcentral.com

**Comment by GiffordChester** [comment]
@zxdong262 I have the console log with me but couldn't post it here. I'll send it to you via email instead.

By the way, this is actually @DylanM72 's issue. I'm just helping out. Thanks.

**Comment by embbnux** [comment]
Hi. @GiffordChester @FilipinaW are you using free RingCentral Developer account to login? Free account doesn't have enough permission to log into those integrationss in production. If you just want to test it, you can use your sandbox account. You can try `toggleEnv()` in chrome console which focus on  widget iframe, and enable toggle button and save.

**Comment by FilipinaW** [comment]
I'm using our regular work RingCentral account.  Not testing anything.

**Comment by embbnux** [comment]
@FilipinaW Can you check if you can login in this page https://ringcentral.github.io/ringcentral-embeddable/ . And can you show some error message from chrome developer JS console?

**Comment by FilipinaW** [comment]
![2019-02-19_9-06-35](https://user-images.githubusercontent.com/47257281/53020934-093e7300-3426-11e9-909c-6287196c25ad.jpg)


I hope this is what you're asking for.

**Comment by embbnux** [comment]
@FilipinaW Can you also check network request list to show that invalid network request response

**Comment by FilipinaW** [comment]
I'm not sure how to get that information for you.

**Comment by steliospapagrigoriou** [comment]
Hello, is there a solution for this? I'm getting the same problem

**Comment by zxdong262** [comment]
Hi @steliospapagrigoriou 

Can you try the latest release, used standalone app:
https://github.com/ringcentral/pipedrive-embeddable-ringcentral-phone-spa/releases/tag/v0.3.10

**Comment by embbnux** [comment]
@steliospapagrigoriou @FilipinaW @DylanM72 It should work now. Previous app id doesn't have  UK and CA scope. Thanks so much for feedback. Please help to check this.

**Comment by steliospapagrigoriou** [comment]
cool thanks it's working now

**Comment by FilipinaW** [comment]
the previous version actually works now, but I will install the update.  thanks for correcting!

**Comment by FilipinaW** [comment]
I installed new version, and now getting below error.  Any ideas?  And btw, when I was able to sign in, it was not recognizing contacts or adding call log.  Still no luck.
{
  "error" : "invalid_client",
  "error_description" : "Invalid client: undefined",
  "errors" : [ {
    "errorCode" : "OAU-153",
    "message" : "Invalid client: undefined",
    "parameters" : [ {
      "parameterName" : "client_id",
      "parameterValue" : "undefined"
    } ]
  } ]
}

**Comment by zxdong262** [comment]
@DylanM72 Sorry, released new version with fix.

**Comment by zxdong262** [comment]
Fixed
